name=input("Name= ")
age=int(input("Age= "))
Class=input("Class= ")
sec=input("Sec= ")
goal=input("Goal=")
idno=input("idno=")
print("----------Student Profile---------")
print("Student Name:",name)
print("Student Age:",age)
print("Student Class:",Class)
print("Student Sec:", sec)
print("Student Goal",goal)
print("Student Id no:",idno)
print("______________Thanks______________")
print("----------------------------------")